language: php

before_script:
  - wget http://download.zeromq.org/zeromq-3.2.2.tar.gz
  - tar xzvf zeromq-3.2.2.tar.gz
  - sh -c "cd zeromq-3.2.2 && ./configure --prefix=/usr/local && sudo make install"
  - git clone https://github.com/mkoppanen/php-zmq.git
  - sh -c "cd php-zmq && phpize && ./configure --with-zmq=/usr/local && make && sudo make install"
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --coverage-text
